Frontend Polish: (ROUND 2)
rlawrenc/PrairieLearn-Ranked pull request #34
Opened 2023-08-03 23:30 UTC by S-Patel25

Added border and hover effect around the scoreboards so far

2023-08-03 23:42 UTC, LouisLP commented on apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
> +<style>
Add these to the CSS file. The words of Scott from 360 echo in your head: no embedded styling!

2023-08-06 20:00 UTC, S-Patel25 commented
@LouisLP what other polishing do we still need?

2023-08-07 21:21 UTC, LouisLP commented
@S-Patel25 
What frontend stuff is on this? Just the gold/silver/bronze cell colors?
Also add a highlight (different background color) on the cell for the current user.

Btw you don't have to include the CSS page, it should be done on plrStudent and plrStaff, so it automatically gets linked.

2023-08-08 05:05 UTC, LouisLP requested changes

2023-08-08 05:05 UTC, LouisLP commented on apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
> + tr:hover {
And if this will go in the CSS file, give a class such as "scoreboard-row" so that it can be differentiated.

2023-08-08 05:05 UTC, LouisLP commented on .github/workflows/cla.yml
Add to different PR when we deal with all this.

2023-08-08 05:05 UTC, LouisLP commented on .github/workflows/main.yml
Add to different PR when we deal with all this.

2023-08-08 05:05 UTC, LouisLP commented on apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
Don't need this, as the CSS is included in the main `ejs` file above it.

2023-08-08 05:05 UTC, LouisLP commented on apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
> +  <%- compiled_stylesheet_tag('PLR.css') %>
Don't need this, as the CSS is included in the main `ejs` file above it.

2023-08-08 05:05 UTC, LouisLP commented on apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
> +  <%- compiled_stylesheet_tag('PLR.css') %>
Don't need this, as the CSS is included in the main `ejs` file above it.

2023-08-09 00:25 UTC, S-Patel25 commented on .github/workflows/cla.yml
Sounds good, the workflow is disabled anyways for the CLA step.

2023-08-09 02:25 UTC, S-Patel25 commented
Ok I added all the changes you requested for, and also in the plrScoreboard.sql, I sorted the live scoreboard by rank ASC as it was showing the top ranks in the bottom instead of the top.

Here is the pic of the highlighted current user (only will highlight if they aren't in the top 3): 
![image](https://github.com/LouisLP/PrairieLearn-Ranked/assets/30157521/90a4859e-e04c-4173-b8de-ac2c0c12f175)

2023-08-09 04:00 UTC, LouisLP approved these changes
LGTM

![okay](https://github.com/LouisLP/PrairieLearn-Ranked/assets/13853873/358ca110-de65-455e-ad33-944e06dc16ee)

2023-08-09 04:00 UTC, merged